version: '2'

services:

  sc-flask:
    command: bash docker/entrypoint.dev.sh
    env_file:
      - server/env/.dev.env
    ports:
      - '5001:5000'

  sc-nginx:
    volumes:
      - ./client/:/opt/sc/static
    command: bash entry-point.dev.sh

  sc-arangodb:
    env_file:
      - server/env/.dev.env
    ports:
      - '8529:8529'

  sc-swagger:
    ports:
      - '8080:8080'

  sc-elasticsearch:
    ports:
    - '9200:9200'
    - '9300:9300'

  sc-livereload:
    build:
      context: ./client/
      dockerfile: Dockerfile-livereload
    command: npm run dev
    container_name: 'sc-livereload'
    labels:
      application: 'sc-livereload'
    volumes:
      - ./client/:/opt/sc/static
    ports:
      - '3000:3000'
      - '3001:3001'

  sc-frontend-tester:
    entrypoint: tail -f /dev/null
    working_dir: /opt/sc/frontend
    volumes:
      - ./client/:/opt/sc/frontend

  sc-frontend-builder:
    command: npm install
    working_dir: /opt/sc/frontend
    volumes:
      - ./client/:/opt/sc/frontend
