version: '2'

services:

  sc-flask:
    volumes:
      - ./server/:/opt/sc/sc-flask
    env_file:
      - server/env/.test.env
    command: bash docker/entrypoint.test.sh

  sc-nginx:
    volumes:
      - ./client/:/opt/sc/static
    command: bash entry-point.test.sh

  sc-arangodb:
    env_file:
      - server/env/.test.env

  sc-frontend-tester:
    entrypoint: tail -f /dev/null
    working_dir: /opt/sc/frontend
    volumes:
      - ./client/:/opt/sc/frontend

# Replace containers we're not testing with dummy ones for a faster build

  sc-pootle:
    image: hello-world

  sc-pootle-mysql:
    image: hello-world
    command: bash amd64/hello-world/hello

  sc-pootle-redis:
    image: hello-world
