version: '2'

services:

  # Containers actually needed for testing:

  sc-flask:
    volumes:
      - ./server/:/opt/sc/sc-flask
    env_file:
      - server/env/.test.env
    command: bash docker/entrypoint.test.sh

  sc-arangodb:
    env_file:
      - server/env/.test.env

  sc-frontend-tester:
    working_dir: /opt/sc/frontend
    volumes:
      - ./client/:/opt/sc/frontend

  # Dummy containers to override unneeded ones from the main docker-compose.yml file and speed up the build:

  sc-nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile-nginx-dummy
    volumes:
      - ./client/:/opt/sc/static

  sc-swagger:
    image: hello-world