version: '2'

services:

  sc-flask:
    build:
      context: ./server/
      dockerfile: docker/Dockerfile-flask
    container_name: 'sc-flask'
    labels:
      application: 'sc-flask'
    env_file:
      - server/env/.base.env
    environment:
      - FLASK_APP=server/app.py
    volumes:
      - socket-volume:/opt/sc/sockets
    expose:
      - '5000'
    depends_on:
      - sc-arangodb

  sc-arangodb:
    image: arangodb/arangodb
    container_name: 'sc-arangodb'
    env_file:
      - server/env/.base.env
    labels:
      application: 'sc-arangodb'
    expose:
      - '8529'
    volumes:
      - db-data-volume:/var/lib/arangodb3

  sc-nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile-nginx
    container_name: 'sc-nginx'
    labels:
      application: 'sc-nginx'
    volumes:
      - nginx-data-volume:/opt/sc/logs/nginx
      - socket-volume:/opt/sc/sockets
    ports:
      - '80:80'
    depends_on:
      - sc-flask
    command: bash entry-point.sh

  sc-elasticsearch:
    build:
      context: ./elasticsearch/
      dockerfile: Dockerfile-elasticsearch
    container_name: 'sc-elasticsearch'
    labels:
      application: 'sc-elasticsearch'
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 2g
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    expose:
      - '9200'
      - '9300'

  sc-swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: 'sc-swagger'
    labels:
      application: 'sc-swagger'
    expose:
      - 8080
    environment:
      - "API_URL=http://127.0.0.1/api/swagger.json"

volumes:
  db-data-volume:
  nginx-data-volume:
  socket-volume:
  elasticsearch-data:
