version: '2'

services:

  sc-flask:
    command: bash docker/entrypoint.dev.sh
    env_file:
      - server/env/.dev.env
    volumes:
      - ./server/:/opt/sc/sc-flask
      - ./client/:/opt/sc/frontend
    ports:
      - '5001:5000'

  sc-nginx:
    volumes:
      - ./client/:/opt/sc/static
    command: bash entry-point.dev.sh

  sc-arangodb:
    env_file:
      - server/env/.dev.env
    ports:
      - '8529:8529'

  sc-swagger:
    ports:
      - '8080:8080'

  sc-elasticsearch:
    ports:
    - '9200:9200'
    - '9300:9300'

  sc-frontend:
    command: npm run dev
    volumes:
      - ./client/elements:/opt/sc/frontend/elements
      - ./client/index.html:/opt/sc/frontend/index.html
      - ./client/redux-store.js:/opt/sc/frontend/redux-store.js
      - ./client/localization/elements:/opt/sc/frontend/localization/elements
    ports:
      - '3000:3000'

  sc-chrome-headless:
    ports:
      - '9222:9222'
