version: '2'

services:

  sc-flask:
    build:
      context: ./server/
      dockerfile: docker/Dockerfile-flask
    container_name: 'sc-flask'
    labels:
      application: 'sc-flask'
    env_file:
      - server/env/.base.env
    environment:
      - FLASK_APP=server/app.py
    volumes:
      - socket-volume:/opt/sc/sockets
      - ./server/:/opt/sc/sc-flask
    expose:
      - '5000'
    depends_on:
      - sc-arangodb

  sc-arangodb:
    image: arangodb/arangodb
    container_name: 'sc-arangodb'
    env_file:
      - server/env/.base.env
    labels:
      application: 'sc-arangodb'
    expose:
      - '8529'
    volumes:
      - db-data-volume:/var/lib/arangodb3

  sc-nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile-nginx
    container_name: 'sc-nginx'
    labels:
      application: 'sc-nginx'
    volumes:
      - nginx-data-volume:/opt/sc/logs/nginx
      - socket-volume:/opt/sc/sockets
      - l10n-ter:/l10n_ter
      - pootle-po:/srv/pootle/po
      - pootle-git:/srv/pootle/git-clones
      - pootle-assets:/usr/local/lib/python2.7/dist-packages/pootle
    ports:
      - '80:80'
      - '2052:2052'
    depends_on:
      - sc-flask
      - sc-pootle
    environment:
      - VIRTUAL_HOST=sc-pootle.docker
      - VIRTUAL_PORT=80

  sc-pootle:
    build:
      context: ./pootle
      dockerfile: Dockerfile
    container_name: 'sc-pootle'
    labels:
      application: 'sc-pootle'
    depends_on:
      - sc-pootle-redis
      - sc-pootle-mysql
    expose:
      - "8000"
    volumes:
      - l10n-ter:/l10n_ter
      - pootle-po:/srv/pootle/po
      - pootle-git:/srv/pootle/git-clones
      - pootle-mysql-socket:/var/run/mysqld
      - pootle-assets:/usr/local/lib/python2.7/dist-packages/pootle
      - ./pootle/supervisord_conf:/etc/supervisor/conf.d/
    environment:
      - SECRET_KEY=SET THIS TO A DJANGO SECRET KEY
    env_file:
      - pootle/environment.yml

  sc-pootle-mysql:
    image: mariadb:10
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    container_name: 'sc-pootle-mysql'
    labels:
      application: 'sc-pootle-mysql'
    volumes:
      - pootle-mysql-data:/var/lib/mysql
      - pootle-mysql-socket:/var/run/mysqld
    ports:
      - "3306:3306"
    env_file:
      - pootle/environment.yml

  sc-pootle-redis:
    image: redis
    container_name: 'sc-pootle-redis'
    labels:
      application: 'sc-pootle-redis'
    expose:
      - "6379"

  sc-pootle-pipeline:
    build:
      context: ./pootle_pipeline/
      dockerfile: Dockerfile-pootle-pipeline
    container_name: 'sc-pootle-pipeline'
    labels:
      application: 'sc-pootle-pipeline'
    volumes:
      - pootle-po:/srv/pootle/po/
      - ./server/server/:/opt/sc/server/
      - ./client/:/opt/sc/frontend/
      - ./pootle_pipeline/:/opt/sc/po_files/

  sc-elasticsearch:
    build:
      context: ./elasticsearch/
      dockerfile: Dockerfile-elasticsearch
    container_name: 'sc-elasticsearch'
    labels:
      application: 'sc-elasticsearch'
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 2g
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    expose:
      - '9200'
      - '9300'

  sc-swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: 'sc-swagger'
    labels:
      application: 'sc-swagger'
    expose:
      - 8080
    environment:
      - "API_URL=http://127.0.0.1/api/swagger.json"

  sc-frontend-tester:
    image: trebuhd/wct-headless:latest
    container_name: 'sc-frontend-tester'
    labels:
      application: 'sc-frontend-tester'

  sc-frontend-builder:
    image: node
    container_name: 'sc-frontend-builder'
    labels:
      application: 'sc-frontend-builder'


volumes:
  db-data-volume:
  nginx-data-volume:
  socket-volume:
  elasticsearch-data:
  pootle-po:
  pootle-git:
  pootle-mysql-data:
  pootle-mysql-socket:
  pootle-assets:
  server-po:
  l10n-ter:
