DOMAIN=pootle.docker

POOTLE_TITLE=SuttaCentral Translation Server
POOTLE_ADMIN_EMAIL=admin@email.foo
POOTLE_ADMIN_PASSWORD=password
POOTLE_ADMIN_NAME=admin


MYSQL_ROOT_PASSWORD=root
MYSQL_USER=pootle
MYSQL_PASSWORD=pootle
MYSQL_DATABASE=pootle_db

